[build-system]
requires = ["setuptools>=42", "setuptools-scm[toml]>=4.1", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
root = "."
write_to = "src/andorSdk3Cameras/_version.py"

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."karabo.middlelayer_device"]
AndorSdk3Camera = "andorSdk3Cameras.AndorSdk3Camera:AndorSdk3Camera"

[project]
dynamic = ["version"]
name = "AndorSdk3Cameras"
keywords = ["Karabo", "SCADA", "camera", "control system"]
authors = [
    {name = "Andrea Parenti", email = "andrea.parenti@xfel.eu"},
]
description = "This package provides a Karabo control device Andor sCMOS cameras."
readme = "README.md"

# Classifiers help users find your project by categorizing it.
#
# For a list of valid classifiers, see https://pypi.org/classifiers/
classifiers = [
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 5 - Production/Stable",

  # Indicate who your project is intended for
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
]

dependencies = ["imageSourcePy ~= 3.0.0", "processingUtils ~= 1.4.2"]
