[build-system]
requires = ["setuptools>=42", "setuptools-scm[toml]>=4.1", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
root = "."
write_to = "src/andorSdk3Cameras/_version.py"

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."karabo.middlelayer_device"]
AndorSdk3Camera = "andorSdk3Cameras.AndorSdk3Camera:AndorSdk3Camera"

[project]
dynamic = ["version"]
name = "AndorSdk3Cameras"
authors = [
    {name = "parenti"},
]
description = ""
readme = "README.md"
dependencies = ["imageSourcePy ~= 3.0.0", "processingUtils ~= 1.4.2"]
